---
- hosts: all
  become: yes
  become_user: postgres
  vars:
    db_user: dbusername
    db_name: dbname
    db_name2: my_database
    db_name3: test1
    db_password: dbpassword
    postgresql_version: 14

  tasks:
    - name: Create the database specified in vars
      become: true
      become_user: postgres
      postgresql_db: name={{ db_name2 }}
        template='template0'
        state=present

    - name: Testing DB to make sure it is available
      postgresql_db: state=present
        db={{ database_name }}

    - name: Run the first_names DB script
      shell: bash -lc "psql {{ database_name }} -f {{ playbook_dir }}/sql/first_names.sql"
      register: psql_result
      failed_when: >
        psql_result.rc != 0
      changed_when: >
        psql_result.rc == 0 and ("INSERT 0 0" not in psql_result.stdout)

    - name: Run the last_names DB script
      shell: bash -lc "psql {{ database_name }} -f {{ playbook_dir }}/sql/last_names.sql"
      register: psql_result
      failed_when: >
        psql_result.rc != 0
      changed_when: >
        psql_result.rc == 0 and ("INSERT 0 0" not in psql_result.stdout)

    - name: Run the functions DB script
      shell: bash -lc "psql {{ database_name }} -f {{ playbook_dir }}/sql/functions.sql"
      register: psql_result
      failed_when: >
        psql_result.rc != 0

## https://github.com/pedroAkiraDanno/pg_faker
